### ISSUE TITLE
[Request] Health Check for Last FSImage Loading

### ISSUE THREAD

**Issue by spearkkk** [marcelmay/hadoop-hdfs-fsimage-exporter#222]
Thank you for nice fsimage exporter.
Im trying to use this exporter for fsimage.
while trying, i found that there is error log for being killed OOM to load huge fsimage with less heap memory size.
That time, there is only error log and there is no other way to inform or notice for this.

So, could you consider adding health checker interface?
or adding anyway to alert this status to developer?

**Comment by marcelmay** [comment]
Hi @spearkkk !

You can use Prometheus also for monitoring the fsimage exporters own health:

1) Monitor and alert on if [service is up in Prometheus](https://samber.github.io/awesome-prometheus-alerts/rules#rule-prometheus-self-monitoring-1-2):
    ```up({job="fsimage-exporter",...})==0```
2) Monitor andd alert on exporter memory ([e.g. llike this](https://samber.github.io/awesome-prometheus-alerts/rules#jvm-1)) and tune the exporter JVM heap sufficiently.

If you run the exporter containerized on e.g. k8s, use a liveness probe on the exposed port.

**Comment by spearkkk** [comment]
@marcelmay 
First of all, thank you for your guideline.
I tried to health check to `/` or `/metrics` when app cannot load fsimage because of heap memory issue.
But application still reply well request(`/`, `/metrics`).
I mean, java application doesn`t exit with heap memory issue because FsImageLoader handles the exception with only logging and the thread is killed.
Could you check about OOM killed for FsImageLoader?

+ On k8s, i wanna set liveness with httpGet `/` or `/metrics`.
Ofc, i can set alert for heap usages but it is also good to set liveness for recovery automatically too.
Thanks!

**Comment by marcelmay** [comment]
What about configuring the JVM with additional flag ```-XX:+ExitOnOutOfMemoryError``` via JAVA_OPTS?

**Comment by spearkkk** [comment]
@marcelmay Thank you!! Really appreciate. you saved my time
