### ISSUE TITLE
Unsupported layout version -64

### ISSUE THREAD

**Issue by rayslinky** [marcelmay/hadoop-hdfs-fsimage-exporter#25]
When trying this against Hadoop 3.1.2, I get

2019-03-20 14:28:12,098 [main] ERROR de.m3y.prometheus.exporter.fsimage.FsImageWatcher  - Can not preload FSImage
java.io.IOException: Unsupported layout version -64

**Comment by marcelmay** [comment]
Hi @rayslinky!

That's probably the erasure coding from Hadoop 3.0.
I'll try to spin up a Hadoop 3.x cluster at the weekend and look into this.

**Comment by marcelmay** [comment]
I can reproduce the issue with a Hadoop 3 fsimage.

This will require an update of hfsa lib with support for Hadoop 3 fsimage format  [feature](https://github.com/marcelmay/hfsa/issues/28).

**Comment by marcelmay** [comment]
Fixed by hfsa lib 1.2.0 update in be58c69ab3267fe46acd2412c29998939ffbcd79
