### ISSUE TITLE
Why not use a Prometheus port

### ISSUE THREAD

**Issue by gsanchezgavier** [marcelmay/hadoop-hdfs-fsimage-exporter#33]
Hi @marcelmay,
Is there any reason i'm missing not to add and use a [new default port](https://github.com/prometheus/prometheus/wiki/Default-port-allocations) for this exporter?
Thanks!

**Comment by marcelmay** [comment]
Thx for pointing this out. 

Just claimed port  9709 for Hadoop HDFS FSImage Exporter, and still have to update docs and code.
