### ISSUE TITLE
fsimage-exporter is not able to load the newer fsimage on its own

### ISSUE THREAD

**Issue by indrarahul2013** [marcelmay/hadoop-hdfs-fsimage-exporter#38]
@marcelmay I have been trying to setup exporter on separate machine than namenode. The new fsimage is getting pushed every 30 mins on the machine where exporter is running from namenode. Still the new metrics are not getting updated. Could you please point me in the right direction why it's not working ?

**Comment by marcelmay** [comment]
- Is the fsImagePath pointing to the directory containing your downloaded fsimage?
- Is the fsimage filename of pattern ```fsimage_\\d+```, eg ```fsimage_000001```?
- When pushing, is the trailing counter increasing for each update? That's how the exporter tries to detect latest version

**Comment by indrarahul2013** [comment]
- Yes the fsImagePath is pointing to the directory where fsimages are getting updated as on first run exporter seems to work fine. 
- fsimage filename pattern is same as hdfs creates. I.e. same pattern as you mentioned.
- the same files are uploaded from the namenode so yes it satisfy this incremental condition.

**Comment by marcelmay** [comment]
Try to enable more verbose logging when starting the exporter:
```java -Dlog.level=DEBUG -jar ....```

**Comment by indrarahul2018** [comment]
Thanks for this info and I enabled this flag too but the exporter seems not to reload the fsimage. You can see the last log line here.
`2020-12-07 08:32:42,745 [pool-1-thread-1] INFO  de.m3y.prometheus.exporter.fsimage.FsImageReporter  - Finished 2126 path stats in 12756ms`

My fsimage directory files says this upon `ls -lah`

```
-rw-r--r-- 1 root root 9903394600 Dec  7 09:39 fsimage_<count>
-rw-r--r-- 1 root root         62 Dec  7 09:39 fsimage_<count>.md5

```
You can see the last modified time is `09:39`, but the last log line of exporter says `2020-12-07 08:32:42,745`.

**Comment by indrarahul2013** [comment]
Thanks for this info and I enabled this flag too but the exporter seems not to reload the fsimage. You can see the last log line here.
`2020-12-07 08:32:42,745 [pool-1-thread-1] INFO  de.m3y.prometheus.exporter.fsimage.FsImageReporter  - Finished 2126 path stats in 12756ms`

My fsimage directory files says this upon `ls -lah`

```
-rw-r--r-- 1 root root 9903394600 Dec  7 09:39 fsimage_<count>
-rw-r--r-- 1 root root         62 Dec  7 09:39 fsimage_<count>.md5

```
You can see the last modified time is `09:39`, but the last log line of exporter says `2020-12-07 08:32:42,745`.

**Comment by marcelmay** [comment]
* Did the `<count>` increase when updating the image? The exporter detects changes if the counter increases only, by looking at the filename (not eg a checksum)
* You might want to watch in the logs for the following lines:
```
... DEBUG de.m3y.prometheus.exporter.fsimage.FsImageWatcher  - Detected changes (old=, new=/Users/mm/projects/hadoop-fsimage-exporter/src/test/resources/fsimage_0001)                                                                                                                                  
...                                                                                                                                                                    
... INFO  de.m3y.prometheus.exporter.fsimage.FsImageUpdateHandler  - Loaded /Users/mm/projects/hadoop-fsimage-exporter/src/test/resources/fsimage_0001 with 0.0MiB in 176ms 
...
... DEBUG de.m3y.prometheus.exporter.fsimage.FsImageWatcher  - Skipping previously discovered /Users/mm/projects/hadoop-fsimage-exporter/src/test/resources/fsimage_0001
```
* Currently, the exporter checks only every minute for local image changes

**Comment by indrarahul2013** [comment]
- Yes, <count> is increasing
- I can see in debug mode sometimes new images are loading and sometimes for longer period even though image is new but it's not getting reloaded.

**Comment by marcelmay** [comment]
The exporter loads/processes an image exactly once per counter increase, then cache the result if it is not changing.

The exporter also loads it asynchronously, as processing the image takes up to minutes (depending on size, eg for millions of  inodes) and would lead to Prometheus scrape timeouts.

There is a metric exposed `fsimage_load_duration_seconds_count` which should increment for each FSImage loaded.

**Comment by marcelmay** [comment]
@indrarahul2013 , any update?

Did my previous explanation about that an fsimage only gets loaded once in the background (triggered by version increment) help?

**Comment by indrarahul2013** [comment]
@marcelmay 
It was working sometimes and sometimes it was breaking. I couldn't find the solution for it, so had to go with other solution.
