### ISSUE TITLE
How can I get the total number of files in hdfs?

### ISSUE THREAD

**Issue by zhangxingdeppon** [marcelmay/hadoop-hdfs-fsimage-exporter#46]
Hi, I need to get  the total  number of files through the exporter metrics, how can I get it?  for example
![image](https://user-images.githubusercontent.com/16789841/118820946-56516e00-b8e9-11eb-9465-c16d01c2947b.png)

I saw the metrics but just have `fsimage_blocks`
![image](https://user-images.githubusercontent.com/16789841/118821361-c06a1300-b8e9-11eb-8262-05efe874134a.png)

**Comment by marcelmay** [comment]
You can use 
* ```fsimage_fsize_count``` for total number of files (I think that's your case)
* ```fsimage_user_fsize_count{user_name="foo"}``` for number of files by users, eg for user 'foo'
* ```fsimage_group_fsize_count{group_name="root"}``` for number of files by group, eg for group 'root'

```fsize``` is of type Histogram, so you get the sum of byte (```_sum```) but also the number (```_count```),
and the distribution (```_bucket```). The distribution can help spotting users with too many small files.

**Comment by zhangxingdeppon** [comment]
> You can use
> 
> * `fsimage_fsize_count` for total number of files (I think that's your case)
> * `fsimage_user_fsize_count{user_name="foo"}` for number of files by users, eg for user 'foo'
> * `fsimage_group_fsize_count{group_name="root"}` for number of files by group, eg for group 'root'
> 
> `fsize` is of type Histogram, so you get the sum of byte (`_sum`) but also the number (`_count`),
> and the distribution (`_bucket`). The distribution can help spotting users with too many small files.

ok, got it, thanks.

**Comment by marcelmay** [comment]
FYI, I added [documentation](https://github.com/marcelmay/hadoop-hdfs-fsimage-exporter#metrics) on the metrics exposed.
