### ISSUE TITLE
It didn't work when use nested regular expression to compute per path stats

### ISSUE THREAD

**Issue by zhangxingdeppon** [marcelmay/hadoop-hdfs-fsimage-exporter#48]
Hi, all, I met a problem, when I  use nested regular expression to compute per path stats, it didn't work, for example:
`'/user/hive/warehouse/.*/.*'`, but `/user/hive/warehouse/ods_ds_test_bdpms.db/.*` is ok, how can do for it?  thanks.
<pre><code># Path where HDFS NameNode stores the fsimage files
# See https://hadoop.apache.org/docs/r2.7.3/hadoop-project-dist/hadoop-hdfs/hdfs-default.xml#dfs.namenode.name.dir
fsImagePath : '/fsimage-location'
# Skip file size distribution for group based stats
skipFileDistributionForGroupStats : false
# Skip file size distribution for user based stats
# Good for figuring out who has too many small files.
skipFileDistributionForUserStats : false

# Compute per path stats
# Supports regex matching for direct child directories
paths:
  - '/tmp'
  - '/datalake/a.*'
  - '/user/m.*'
  - '/user/hive/warehouse/.*/.*'
#  - '/user/hive/warehouse/ods_ds_test_bdpms.db/.*'
# Skip file size distribution for path based stats
skipFileDistributionForPathStats : false

# Path sets are grouped paths by an identifier
pathSets:
  'userMmAndFooAndAsset1' : [
    '/datalake/asset3',
    '/user/mm',
    '/user/foo'
    ]
  'datalakeAsset1and2' : [
    '/datalake/asset1',
    '/datalake/asset2'
    ]
# Skip file size distribution for path sets based stats
skipFileDistributionForPathSetStats : false
# Configure file size distribution buckets, supporting IEC units of KiB, MiB, GiB, TiB, PiB
fileSizeDistributionBuckets: ['0','1MiB', '32MiB', '64MiB', '128MiB', '1GiB', '10GiB']
</code></pre>

**Comment by marcelmay** [comment]
Only 'direct child directories' are supported, as stated in the comment on paths.

So you'll need to either do
* /user/hive/warehouse/ods_ds_test_bdpms.db/.*
* /user/hive/warehouse/another.db/.*

I would have expected that you want per specific warehouse metrics:
* /user/hive/warehouse/.*.db

Would the user or group wise metrics maybe fit better to your case (if these paths are owned by different users or groups)?

**Comment by zhangxingdeppon** [comment]
> Would the user or group wise metrics maybe fit better to your case (if these paths are owned by different users or groups)?
@marcelmay Okay,  it's special about us that the same user or group maybe create multiple databases or tables, and need to compute per path stats,  so only just use this way that list all the database:
* /user/hive/warehouse/ods_ds_test_bdpms.db/.*
* /user/hive/warehouse/another.db/.*

**Comment by marcelmay** [comment]
Should be implemented in latest release [1.4.5](https://github.com/marcelmay/hadoop-hdfs-fsimage-exporter/releases/tag/release-1.4.5) by #73 

I'm closing this, any feedback regarding 1.4.5 appreciated
