### ISSUE TITLE
Docker configuration folder changed

### ISSUE THREAD

**Issue by DieterDP-ng** [marcelmay/hadoop-hdfs-fsimage-exporter#71]
Hi,

just wanted to flag that in [your recent commit](https://github.com/marcelmay/hadoop-hdfs-fsimage-exporter/commit/2e5d960a10bcf169a72a8405a37306a4c486bd8a), the configuration folder was (accidentally?) changed from `/opt/fsimage-exporter` to `/opt/fsimage_exporter`.

Thanks for your work on this component!

**Comment by marcelmay** [comment]
Will revert this accidental change.

Thx alot, @DieterDP-ng !
