### ISSUE TITLE
config.yml paths  How do I support cross-directory re syntax

### ISSUE THREAD

**Issue by liangrui1988** [marcelmay/hadoop-hdfs-fsimage-exporter#72]
for example I need all paths information for /hive/db/table
```
paths:  
   - '/hive_warehouse/*/*'
```

After I do this, I do not list all the table information. Why is this?

**Comment by marcelmay** [comment]
The exporter uses [Java Regexp](https://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html),
but only matches lowest directories currently:

```
paths:  
   - '/hive_warehouse/db1/.*'
   - '/hive_warehouse/db2/.*'
   - ...
```

I'll extend the exporter to match directories on each level (#73)

**Comment by marcelmay** [comment]
@liangrui1988 , I plan to add this to the next release this wednesday

**Comment by marcelmay** [comment]
@liangrui1988 : Can you try release 1.4.5 using this config:
```
paths:  
   - '/hive_warehouse/.*/.*'
```
Any feedback regarding new 1.4.5 release appreciated.
