### ISSUE TITLE
How to config the fsImagePath in the example.yml file when deploy hadoop-hdfs-fsimage-exporter not in namenode node

### ISSUE THREAD

**Issue by 13416157913** [marcelmay/hadoop-hdfs-fsimage-exporter#82]
Hi,
   I want to ask how to config the fsImagePath in the example.yml file when deploy hadoop-hdfs-fsimage-exporter not in namenode node.

**Comment by marcelmay** [comment]
Hi @13416157913 ,

you nee the fsimage data available on a local path.

I recommend to run the exporter on the same instance as the NameNode, to avoid having to transfer the (possibly large) fsimage over the network.

If you can not avoid it, create e.g. a script periodically copying it from the NameNode (copy to local FS and rename it to location watched by the exporter).

Using ```hdfs dfsadmin -fetchImage...``` is IMHO not a solution, as it puts too much load on the NameNode..

**Comment by 13416157913** [comment]
> Hi @13416157913 ,
> 
> you nee the fsimage data available on a local path.
> 
> I recommend to run the exporter on the same instance as the NameNode, to avoid having to transfer the (possibly large) fsimage over the network.
> 
> If you can not avoid it, create e.g. a script periodically copying it from the NameNode (copy to local FS and rename it to location watched by the exporter).
> 
> Using `hdfs dfsadmin -fetchImage...` is IMHO not a solution, as it puts too much load on the NameNode..

Thanks your answer.
