### ISSUE TITLE
Fsimage metrics are not getting exported

### ISSUE THREAD

**Issue by prathapsagar** [marcelmay/hadoop-hdfs-fsimage-exporter#83]
Hi I am using a helm based installation of hadoop 3.3.4. and when I use the exporter only basic jvm metrics are getting exported and not any fs image metrics. Below is my config.yaml. Can someone suggest if I am missing anything here.

  fsImagePath : '/dfs/name/current` 
    skipFileDistributionForGroupStats : true 
    skipFileDistributionForUserStats : false 
    skipFileDistributionForPathStats : true 
    skipFileDistributionForPathSetStats : true 
    paths: 
      - '/hbase' 
    fileSizeDistributionBuckets: ['0','1MiB', '32MiB', '64MiB', '128MiB', '1GiB', '10GiB']

**Comment by marcelmay** [comment]
Hi @prathapsagar 

1) Check fsimage location
   Are there any fsimages at given location, e.g.  do a `ls -l /dfs/name/current/fsimage_000*`
   If you start up a local test hadoop cluster, it will take a while (depening on NameNode config) till first fsimages are available.

2)  Check if correct location
    Expected location would be from hdfs-site.xml property `dfs.namenode.name.dir` in the `current` sub directory:
     `${dfs.namenode.name.dir}/currenct`

3) Check the log output of the exporter for errors/warnings

4) Check exporter [own metrics](https://github.com/marcelmay/hadoop-hdfs-fsimage-exporter#exporter-internal-metrics), e.g. `fsimage_load_file_size_bytes` is zero or does `fsimage_scrape_errors_total` indicate errors

**Comment by prathapsagar** [comment]
I am getting this warning : WARN  de.m3y.prometheus.exporter.fsimage.FsImageWatcher  - Can not detect fsimage file : No fsimage file(s) found in /dfs/name/current matching pattern fsimage_\d+.
But I can see these files in the path dfs/name/current: 
/fsimage_0000000000000011013
./fsimage_0000000000000012481.md5
./fsimage_0000000000000012481
./fsimage_0000000000000011013.md5

**Comment by prathapsagar** [comment]
Hi @marcelmay this error as caused when I used the latest the image for hadoop 3.3.4 and now got fixed when using the image marcelmay/hadoop-hdfs-fsimage-exporter:1.4.2 can you please check why this is issue is cause in the latest image. Thank you!
